version: '3'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  api:
    build:
      context: api
    ports:
      - "3080:3080"
    expose:
      - "3080"
    volumes:
      - ./api:/usr/src/app/api
        # I think this mapping has to do with how hot reloading is handled with container restarts...
      - /usr/src/app/talent-api/node_modules
  ui:
    build:
      context: ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./ui:/usr/src/app/ui
        # I think this mapping has to do with how hot reloading is handled with container restarts...
      - /usr/src/app/talent-ui/node_modules
